name: searchbase
version: 1.0.0-alpha
description: >-
  SearchBase is a library to build the search UIs with Elasticsearch.
homepage: https://github.com/appbaseio/flutter-searchbox
documentation: https://docs.appbase.io/docs/reactivesearch/searchbase/overview/apireference/
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  http: ^0.12.2
  collection: ^1.14.13
dev_dependencies:
  test: ^1.15.7
