name: searchbase
version: 2.0.0
description: >-
  SearchBase is a library to build the search UIs with Elasticsearch.
homepage: https://github.com/appbaseio/flutter-searchbox
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  http: ^0.13.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.5
